image: 
  name: pandoc/core
  # Override default entry point.
  # The GitLab runner expects that the image has no entrypoint 
  # or that the entrypoint is prepared to start a shell command. 
  entrypoint: [""]

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - apk add --no-cache tree git
    - mkdir public
    - chmod +x markdown_tools/*.sh
    - markdown_tools/md_to_html.sh -m .pubhtml_manifest -d public
#    - for i in $(ls lectures/scripts/*/*); do tools/code_to_html.sh -i $i -d public; done
    - find public -type d -exec tree {} -H '.' -T "$CI_PROJECT_TITLE" -P "*.html" -I "index.html" --noreport --charset utf-8 -o {}/index.html \;
  artifacts:
    paths:
      - public
